--2.1
/* SELECT A.NOME
FROM TB_IMPIEGATI  A,TB_ORDINI B
WHERE A.ID_IMP = B.ID_IMP AND
B.CLIENTE = 'Fiat'
ORDER BY A.NOME; */
--2.2
/* SELECT A.NOME,B.ID_ORDINE
FROM TB_IMPIEGATI  A,TB_ORDINI B
WHERE A.ID_IMP = B.ID_IMP AND
B.DATA_ORDINE BETWEEN '01/02/2014' AND '28/02/2024'
ORDER BY B.CLIENTE; */
--2.3
/* SELECT F.ID_FORNITORE,P.ID_PROD,P.IN_COMMERCIO
FROM MARKET_PRODOTTI P,MARKET_FORNITORI F
WHERE P.ID_FORNITORE = F.ID_FORNITORE
ORDER BY P.IN_COMMERCIO; */
--2.4
/* SELECT A.ID_LIBRO
FROM TB_02_LIBRI A,TB_02_PRESTITO_LIBRO B
WHERE A.ID_LIBRO = B.ID_LIBRO AND A.ID_LIBRO LIKE '%7'; */
--2.5
/* SELECT A.TITOLO,A.GENERE,B.DATA_PROIEZIONE
FROM FILM A,PROIEZIONI B
WHERE A.COD_FILM = B.COD_FILM AND
EXTRACT(MONTH FROM B.DATA_PROIEZIONE) = '12'
ORDER BY A.GENERE DESC; */
--2.6
/* SELECT A.TITOLO,A.GENERE,B.DATA_PROIEZIONE
FROM FILM A,PROIEZIONI B,SALE C
WHERE A.COD_FILM = B.COD_FILM AND B.COD_SALA = C.COD_SALA AND
EXTRACT(MONTH FROM B.DATA_PROIEZIONE) IN ('9','11','10') AND 
C.CITTA = 'Napoli'
ORDER BY A.GENERE; */
--2.7
/* SELECT A.TITOLO,C.COGNOME
FROM FILM A,RECITA B,ATTORI C
WHERE A.COD_FILM = B.COD_FILM AND B.ID_ATT = C.ID_ATT  AND
C.COGNOME LIKE '__i%'
ORDER BY A.TITOLO; */
--2.8
/* SELECT A.TITOLO,C.NOME_SALA
FROM FILM A,PROIEZIONI B,SALE C
WHERE A.COD_FILM = B.COD_FILM AND B.COD_SALA = C.COD_SALA AND
B.DATA_PROIEZIONE BETWEEN '01/11/2004' AND '31/12/2008' AND
C.CITTA = 'Roma'
ORDER BY A.TITOLO,2 DESC; */
--2.9
/* SELECT A.TITOLO
FROM TB_02_LIBRI A,TB_02_PRESTITO_LIBRO B,TB_02_UTENTI C
WHERE A.ID_LIBRO = B.ID_LIBRO 
AND B.ID_STUDENTE = C.ID_STUDENTE
AND C.COGNOME = 'Vallieri'
ORDER BY B.DT_INI_PRES; */
--2.10
/* SELECT C.NOME,C.COGNOME,A.TITOLO
FROM TB_02_LIBRI A,TB_02_PRESTITO_LIBRO B,TB_02_UTENTI C
WHERE A.ID_LIBRO = B.ID_LIBRO AND B.ID_STUDENTE = C.ID_STUDENTE
AND B.DT_FIN_PRES IS NULL
ORDER BY B.ID_PRESTITO DESC,C.COGNOME; */
--2.11
/* SELECT A.NOME,A.COGNOME,B.NOME_UFFICIO
FROM DIPENDENTI A,UFFICI B
WHERE A.COD_UFF = B.COD_UFF AND
REGEXP_LIKE (A.COGNOME,'^[D-J]')
ORDER BY A.COGNOME; */
--2.12
/* SELECT A.NOME,A.COGNOME,B.COD_UFF,A.RUOLO
FROM DIPENDENTI A,UFFICI B
WHERE A.COD_UFF = B.COD_UFF AND
A.COGNOME BETWEEN 'A02' AND 'D22'AND
NOT A.RUOLO = 'Magazzinere'AND
A.COGNOME LIKE 'A%'
ORDER BY B.NOME_UFFICIO,A.COGNOME,A.NOME; */
--2.13
/* SELECT B.NOME_UFFICIO,A.COGNOME,A.NOME,A.COD_DIP,B.RESP_UFF
FROM DIPENDENTI A,UFFICI B
WHERE A.COD_DIP = B.RESP_UFF
ORDER BY A.COGNOME; */
--2.14
SELECT DISTINCT A.COD_PROG,A.NOME_PROG
FROM PROGETTI A,TASK_DIPENDENTI B
WHERE A.COD_PROG = B.ID_TASK AND
A.NOME_PROG LIKE 'B%' AND A.NOME_PROG LIKE '%2'
ORDER BY A.COD_PROG,B.NUM_TASK;