/* 1.1 Istruzione Select.
SELECT COD_DIP,COGNOME,DT_NASCITA,BONUS,STIPENDIO
FROM DIPENDENTI
WHERE BONUS>500
ORDER BY STIPENDIO DESC;
--1.2 Istruzione Select.
SELECT COGNOME,NOME,COD_UFF
FROM DIPENDENTI
WHERE NOME LIKE '%i'
ORDER BY COD_UFF DESC;
--1.3
SELECT DISTINCT LIVELLO_ISTRUZIONE
FROM DIPENDENTI
ORDER BY LIVELLO_ISTRUZIONE DESC;
--1.4
SELECT COD_PROG,COD_DIP
FROM TASK_DIPENDENTI
WHERE COD_DIP>100 AND COD_PROG BETWEEN 'I' AND 'N'
ORDER BY 2;
--1.5
SELECT COGNOME,BONUS,STIPENDIO,DT_ASSUNZ
FROM DIPENDENTI
WHERE SESSO = 'U' AND DT_ASSUNZ BETWEEN '01/08/23' AND '31/12/24'
ORDER BY COGNOME;
--1.6 Istruzione Select con operatori logici.
SELECT COGNOME,STIPENDIO,BONUS,COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 3000 AND BONUS > 400) OR 
(BONUS>500 AND COMMISSIONI<300);
ORDER BY COGNOME DESC
--1.7
SELECT COGNOME,STIPENDIO,BONUS,COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 2500) AND 
((BONUS < 400) OR 
((BONUS > 500) AND (COMMISSIONI > 300)))
ORDER BY COGNOME DESC;
--1.8
SELECT COD_PROG,NUM_TASK,DT_INI_TASK,DT_FIN_TASK
FROM TASK_DIPENDENTI
WHERE (COD_PROG LIKE 'A%')
AND ID_TASK IN (10,80,180)
ORDER BY COD_PROG DESC;
--1,9
SELECT COD_UFF,RESP_UFF
FROM UFFICI
WHERE RESP_UFF IS NOT NULL
ORDER BY RESP_UFF;
--1.10
SELECT COGNOME,STIPENDIO,COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 2500) AND 
EXTRACT(YEAR FROM DT_ASSUNZ) > 2022
ORDER BY COGNOME DESC;
--1.11*/
