/* 1.1 Istruzione Select.
SELECT COD_DIP,COGNOME,DT_NASCITA,BONUS,STIPENDIO
FROM DIPENDENTI
WHERE BONUS>500
ORDER BY STIPENDIO DESC;
--1.2 Istruzione Select.
SELECT COGNOME,NOME,COD_UFF
FROM DIPENDENTI
WHERE NOME LIKE '%i'
ORDER BY COD_UFF DESC;
--1.3
SELECT DISTINCT LIVELLO_ISTRUZIONE
FROM DIPENDENTI
ORDER BY LIVELLO_ISTRUZIONE DESC;
--1.4
SELECT COD_PROG,COD_DIP
FROM TASK_DIPENDENTI
WHERE COD_DIP>100 AND COD_PROG BETWEEN 'I' AND 'N'
ORDER BY 2;
--1.5
SELECT COGNOME,BONUS,STIPENDIO,DT_ASSUNZ
FROM DIPENDENTI
WHERE SESSO = 'U' AND DT_ASSUNZ BETWEEN '01/08/23' AND '31/12/24'
ORDER BY COGNOME;
--1.6 Istruzione Select con operatori logici.
SELECT COGNOME,STIPENDIO,BONUS,COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 3000 AND BONUS > 400) OR 
(BONUS>500 AND COMMISSIONI<300);
ORDER BY COGNOME DESC
--1.7
SELECT COGNOME,STIPENDIO,BONUS,COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 2500) AND 
((BONUS < 400) OR 
((BONUS > 500) AND (COMMISSIONI > 300)))
ORDER BY COGNOME DESC;
--1.8
SELECT COD_PROG,NUM_TASK,DT_INI_TASK,DT_FIN_TASK
FROM TASK_DIPENDENTI
WHERE (COD_PROG LIKE 'A%')
AND ID_TASK IN (10,80,180)
ORDER BY COD_PROG DESC;
--1,9
SELECT COD_UFF,RESP_UFF
FROM UFFICI
WHERE RESP_UFF IS NOT NULL
ORDER BY RESP_UFF;
--1.10
SELECT COGNOME,STIPENDIO,COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 2500) AND 
EXTRACT(YEAR FROM DT_ASSUNZ) > 2022
ORDER BY COGNOME DESC;
--1.11
SELECT COD_DIP,COGNOME,STIPENDIO,BONUS
FROM DIPENDENTI
WHERE BONUS BETWEEN 800 AND 900
ORDER BY BONUS,COD_DIP;
--1.12
SELECT COD_DIP,COGNOME,STIPENDIO,COD_UFF
FROM DIPENDENTI
WHERE COD_UFF BETWEEN 'A00' AND 'C01'
ORDER BY COGNOME,COD_DIP DESC;
--1.13
SELECT COD_PROG,NOME_PROG
FROM PROGETTI
WHERE NOME_PROG NOT LIKE '%Sviluppo%'
ORDER BY COD_PROG;
--1.14
SELECT COD_UFF,NOME_UFFICIO
FROM UFFICI
WHERE COD_UFF LIKE '_1_'
ORDER BY COD_UFF DESC;
--1.15
SELECT COGNOME,NOME,INIZIALI,STIPENDIO
FROM DIPENDENTI
WHERE (RUOLO NOT 'Amministratore' OR 'Manager')
AND
((INIZIALI NOT LIKE '%FL%') OR (INIZIALI NOT LIKE '%TC%')) AND STIPENDIO BETWEEN 2500 AND 2630
ORDER BY STIPENDIO DESC;
--1.16
SELECT NOME_SALA
FROM SALE
WHERE NOME_SALA LIKE '___A%' AND NOME_SALA LIKE '______A%'
ORDER BY NOME_SALA;
--1.17
SELECT TITOLO,DATA_PROD
FROM FILM
WHERE GENERE = 'Drammatico' AND NAZIONALITA IN ('USA','Spagnolo')  
AND DATA_PROD BETWEEN '01/01/00' AND '31/12/07'
ORDER BY DATA_PROD;
--1.26 Select con funzioni Sql che agiscono su più righe.
SELECT SUM(STIPENDIO) as SOMMA_STIPENDI_UFF_B01
FROM  DIPENDENTI
WHERE COD_UFF = 'B01';
--1.27
SELECT COUNT(*) as Totale_DIPENDENTI
FROM DIPENDENTI
WHERE COMMISSIONI BETWEEN 200 AND 400
AND NOME LIKE '%o%'
AND RUOLO LIKE '%Manager%'
AND EXTRACT(MONTH FROM DT_ASSUNZ) IN ('02','08');
--1.28
SELECT MIN(STIPENDIO) as STIPENDIO_MINIMO,
MAX(STIPENDIO) as STIPENDIO_MASSIMO,
AVG(STIPENDIO) as  STIPENDIO_MEDIO
FROM DIPENDENTI
WHERE COMMISSIONI BETWEEN 200 AND 400
AND NOME LIKE '%o%'
AND RUOLO LIKE '%Manager%'
AND EXTRACT(MONTH FROM DT_ASSUNZ) IN ('02','08','09','11','12');
*/