/* 1.1 Istruzione Select.
SELECT COD_DIP,COGNOME,DT_NASCITA,BONUS,STIPENDIO
FROM DIPENDENTI
WHERE BONUS>500
ORDER BY STIPENDIO DESC;
--1.2 Istruzione Select.
SELECT COGNOME,NOME,COD_UFF
FROM DIPENDENTI
WHERE NOME LIKE '%i'
ORDER BY COD_UFF DESC;
--1.3
SELECT DISTINCT LIVELLO_ISTRUZIONE
FROM DIPENDENTI
ORDER BY LIVELLO_ISTRUZIONE DESC;
--1.4
SELECT COD_PROG,COD_DIP
FROM TASK_DIPENDENTI
WHERE COD_DIP>100 AND COD_PROG BETWEEN 'I' AND 'N'
ORDER BY 2;
*/